/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("application")
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}
application {
    mainClass.set("Main")
}

dependencies {
    implementation("com.alphacephei:vosk:0.3.45")
    implementation("net.java.dev.jna:jna:5.13.0")
}

group = "com.mycompany.app"
version = "1.0-SNAPSHOT"
description = "my-app"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
